local _, addon = ...

local function HoverNameUpdate()
  local f = addon.HoverName and addon.HoverName.UpdateFrame
  if f then pcall(f) end
end

addon.MBLib.Settings:Add({
  {
    Key = "Display_CursorAnchor",
    Name = "Cursor Anchor",
    Description = "Where the frame appears relative to the cursor.",
    Group = "Display",
    Type = "dropdown",
    Options = {
      { name = "Top", value = "TOP" },
      { name = "Bottom", value = "BOTTOM" },
      { name = "Left", value = "LEFT" },
      { name = "Right", value = "RIGHT" },
      { name = "Top Left", value = "TOPLEFT" },
      { name = "Top Right", value = "TOPRIGHT" },
      { name = "Bottom Left", value = "BOTTOMLEFT" },
      { name = "Bottom Right", value = "BOTTOMRIGHT" },
    },
    Default = "TOP",
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_CursorOffsetVertical",
    Name = "Vertical Offset",
    Description = "Vertical offset from the cursor. Positive values shift the frame up, negative values shift it down.",
    Group = "Display",
    Type = "slider",
    Min = -200,
    Max = 200,
    Step = 1,
    Default = 4,
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_CursorOffsetHorizontal",
    Name = "Horizontal Offset",
    Description = "Horizontal offset from the cursor. Positive values shift the frame right, negative values shift it left.",
    Group = "Display",
    Type = "slider",
    Min = -200,
    Max = 200,
    Step = 1,
    Default = 0,
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_FontSize",
    Name = "Font Size",
    Description = "Basic size of all texts displayed when hovering",
    Group = "Display",
    Type = "slider",
    Min = 8,
    Max = 30,
    Step = 1,
    Default = 12,
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_FontType",
    Name = "Font Type",
    Description = "The font family of all texts displayed when hovering",
    Group = "Display",
    Type = "dropdown",
    Options = { "Friz Quadrata TT" },
    Default = "Friz Quadrata TT",
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_FontOutline",
    Name = "Font Outline",
    Description = "Outline style for hover name text (if supported by the font)",
    Group = "Display",
    Type = "dropdown",
    Options = {
      { name = "None", value = "NONE" },
      { name = "Outline", value = "OUTLINE" },
      { name = "Thick Outline", value = "THICKOUTLINE" },
      { name = "Monochrome Outline", value = "MONOCHROMEOUTLINE" },
    },
    Default = "OUTLINE",
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_BackgroundEnabled",
    Name = "Show Background",
    Description = "Show a background behind the hover text.",
    Group = "Display",
    Type = "checkbox",
    Default = false,
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_BackgroundColor",
    Name = "Background Color",
    Description = "The color of the background behind the hover text.",
    Group = "Display",
    Type = "dropdown",
    Options = {
      { name = "Black", value = "BLACK" },
      { name = "White", value = "WHITE" },
      { name = "Red", value = "RED" },
      { name = "Blue", value = "BLUE" },
      { name = "Green", value = "GREEN" },
      { name = "Yellow", value = "YELLOW" },
      { name = "Purple", value = "PURPLE" },
      { name = "Orange", value = "ORANGE" },
      { name = "Brown", value = "BROWN" },
    },
    Default = "BLACK",
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_BackgroundAlpha",
    Name = "Background Transparency",
    Description = "Transparency for the background (0 = fully transparent, 100 = fully opaque)",
    Group = "Display",
    Type = "slider",
    Min = 0,
    Max = 100,
    Step = 1,
    Default = 50,
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Display_BackgroundPadding",
    Name = "Background Padding",
    Description = "Add additional padding around the background.",
    Group = "Display",
    Type = "slider",
    Min = 0,
    Max = 20,
    Step = 1,
    Default = 2,
    OnChange = HoverNameUpdate,
  },
  {
    Key = "Player_ClassColor",
    Name = "Class Colors",
    Description = "Color a player's name by their class",
    Group = "Player",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "Player_ShowLevel",
    Name = "Show Level",
    Description = "Show a player's level",
    Group = "Player",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "Player_LevelColor",
    Name = "Level Color",
    Description = "Color a player's level in comparison to your own level",
    Group = "Player",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "Player_ShowTarget",
    Name = "Show Target",
    Description = "Show the name of a player's current target",
    Group = "Player",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "Player_ShowStatus",
    Name = "Show Status",
    Description = "Show a player's status (AFK / DND / PvP)",
    Group = "Player",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "Player_ShowGuildName",
    Name = "Show Guild name",
    Description = "Show a player's guild name",
    Group = "Player",
    Type = "checkbox",
    Default = false,
  },
  {
    Key = "Player_ShowGuildRank",
    Name = "Show Guild rank",
    Description = "Show a player's guild rank",
    Group = "Player",
    Type = "checkbox",
    Default = false,
  },
  {
    Key = "Player_ShowRace",
    Name = "Show Race",
    Description = "Show a player's race",
    Group = "Player",
    Type = "checkbox",
    Default = false,
  },
  {
    Key = "Player_ShowFaction",
    Name = "Show Faction",
    Description = "Show a player's faction",
    Group = "Player",
    Type = "checkbox",
    Default = false,
  },
  {
    Key = "NPC_ColorState",
    Name = "Standing Colors",
    Description = "Color an NPC's name by their standing towards you (dead / hostile / neutral / friendly)",
    Group = "NPC",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "NPC_ShowLevel",
    Name = "Show Level",
    Description = "Show an NPC's level",
    Group = "NPC",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "NPC_LevelColor",
    Name = "Level Color",
    Description = "Color an NPC's level in comparison to your own level",
    Group = "NPC",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "NPC_ShowTarget",
    Name = "Show Target",
    Description = "Show the name of an NPC's current target",
    Group = "NPC",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "NPC_ShowClassification",
    Name = "Show Classification",
    Description = "Show an NPC's classification (rare / elite / boss)",
    Group = "NPC",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "NPC_ShowFaction",
    Name = "Show Faction",
    Description = "Show an NPC's faction",
    Group = "NPC",
    Type = "checkbox",
    Default = false,
  },
  {
    Key = "NPC_ShowCreatureType",
    Name = "Show Creature Type",
    Description = "Show an NPC's creature type (e.g. Beast, Humanoid, Demon, etc.)",
    Group = "NPC",
    Type = "checkbox",
    Default = false,
  },
  {
    Key = "Quest_Show",
    Name = "Show Information",
    Description = "Show info below the target's name if this is needed for quests, dailies, world quests or objectives.",
    Group = "Quests / Objectives",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "Quest_ShowCompleted",
    Name = "Show Completed",
    Description = "Still show completed objectives in the hover information, until all are completed.",
    Group = "Quests / Objectives",
    Type = "checkbox",
    Default = true,
  },
  {
    Key = "Integrations_Rarity",
    Name = "Rarity",
    Description = "Show information from the 'Rarity' addon when it is installed",
    Group = "Integrations",
    Type = "checkbox",
    Default = false,
    Hide = true,
  },
})